# Generated by Django 5.0.6 on 2026-08-26 05:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shipment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "route_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("alert_type", models.CharField(default="GALE_WARNING", max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "weather_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"],
                        name="weather_ale_status_51c51b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.CharField(db_index=True, max_length=128)),
                (
                    "quote_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "route_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0, help_text="Composite weather risk score (0-100)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "storm_risk",
                    models.FloatField(
                        default=0.0, help_text="Storm risk score (0-100)"
                    ),
                ),
                (
                    "rainfall_risk",
                    models.FloatField(
                        default=0.0,
                        help_text="Precipitation/Rainfall risk score (0-100)",
                    ),
                ),
                (
                    "wind_risk",
                    models.FloatField(
                        default=0.0, help_text="Gale/Wind speed risk score (0-100)"
                    ),
                ),
                (
                    "wave_risk",
                    models.FloatField(
                        default=0.0, help_text="Ocean wave/swell risk score (0-100)"
                    ),
                ),
                (
                    "temperature_risk",
                    models.FloatField(
                        default=0.0, help_text="Temperature extreme risk score (0-100)"
                    ),
                ),
                (
                    "delay_probability",
                    models.FloatField(
                        default=0.0,
                        help_text="Predicted probability of transit delay (0.0 to 1.0 or 0-100%)",
                    ),
                ),
                (
                    "assessment_status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                            ("STALE", "Stale"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="open-meteo", max_length=64)),
                (
                    "provider_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0, help_text="Confidence metric (0.0 - 1.0)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "weather_assessments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment_id", "created_at"],
                        name="weather_ass_shipmen_0ac7d7_idx",
                    ),
                    models.Index(
                        fields=["route_id"], name="weather_ass_route_i_f5c8ef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("route_id", models.CharField(db_index=True, max_length=128)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "observation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=20.0, help_text="Surface temperature in °C"
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(default=0.0, help_text="Wind speed in knots/kmh"),
                ),
                (
                    "wind_direction",
                    models.FloatField(
                        default=0.0, help_text="Wind direction in degrees (0-360)"
                    ),
                ),
                (
                    "rainfall",
                    models.FloatField(default=0.0, help_text="Precipitation in mm/h"),
                ),
                (
                    "wave_height",
                    models.FloatField(
                        default=0.0, help_text="Significant wave height in meters"
                    ),
                ),
                (
                    "visibility",
                    models.FloatField(default=10.0, help_text="Visibility in km"),
                ),
                (
                    "pressure",
                    models.FloatField(
                        default=1013.25, help_text="Atmospheric pressure in hPa"
                    ),
                ),
                ("weather_condition", models.CharField(default="Clear", max_length=64)),
                ("storm_detected", models.BooleanField(default=False)),
                ("storm_type", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "storm_severity",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("provider", models.CharField(default="open-meteo", max_length=64)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weather_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="weather.weatherassessment",
                    ),
                ),
            ],
            options={
                "db_table": "weather_observations",
                "ordering": ["observation_time"],
                "indexes": [
                    models.Index(
                        fields=["route_id", "observation_time"],
                        name="weather_obs_route_i_afe298_idx",
                    )
                ],
            },
        ),
    ]
