# Generated by Django 6.0.7 on 2026-09-04 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_id", models.CharField(db_index=True, max_length=64)),
                ("actor_role", models.CharField(default="system", max_length=32)),
                (
                    "actor_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("action", models.CharField(db_index=True, max_length=64)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("SHIPMENT", "Shipment"),
                            ("QUOTE", "Quote"),
                            ("CUSTOMS_CHECK", "Customs Compliance Check"),
                            ("RISK_ASSESSMENT", "Risk Assessment"),
                            ("USER", "User"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("reason", models.TextField(blank=True, default="")),
                ("changes", models.JSONField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    )
                ],
            },
        ),
    ]
