# Generated by Django 6.0.7 on 2026-09-04 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrchestrationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.CharField(db_index=True, max_length=64)),
                (
                    "quote_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("DEGRADED", "Completed with degraded agents"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("duration_ms", models.IntegerField(default=0)),
                ("degraded_agents", models.JSONField(blank=True, default=list)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentInvocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("ROUTE", "Route Agent"),
                            ("PRICING", "Pricing Agent"),
                            ("WEATHER", "Weather Agent"),
                            ("CUSTOMS", "Customs Agent"),
                            ("RISK", "Risk Agent"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Succeeded"),
                            ("DEGRADED", "Fell back"),
                            ("FAILED", "Failed"),
                        ],
                        default="OK",
                        max_length=16,
                    ),
                ),
                ("duration_ms", models.IntegerField(default=0)),
                ("summary", models.CharField(blank=True, default="", max_length=256)),
                ("error", models.TextField(blank=True, default="")),
                ("output", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invocations",
                        to="orchestrator.orchestrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
