# Generated by Django 5.0.6 on 2026-08-26 05:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomsRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin_country", models.CharField(db_index=True, max_length=64)),
                ("destination_country", models.CharField(db_index=True, max_length=64)),
                ("hs_code", models.CharField(blank=True, db_index=True, max_length=16)),
                ("commodity", models.CharField(blank=True, max_length=128)),
                ("incoterm", models.CharField(blank=True, max_length=16)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("TARIFF", "Tariff / Duty"),
                            ("RESTRICTION", "Trade Restriction"),
                            ("PROHIBITION", "Prohibited Good"),
                            ("DOCUMENT", "Mandatory Documentation"),
                            ("INSPECTION", "Physical/Quarantine Inspection"),
                            ("SANCTION", "Trade Sanction"),
                        ],
                        default="DOCUMENT",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                ("mandatory", models.BooleanField(default=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customs_requirements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomsComplianceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.CharField(db_index=True, max_length=128)),
                (
                    "quote_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("origin_country", models.CharField(max_length=64)),
                ("destination_country", models.CharField(max_length=64)),
                ("hs_code", models.CharField(max_length=16)),
                ("commodity", models.CharField(max_length=128)),
                ("incoterm", models.CharField(blank=True, max_length=16)),
                (
                    "readiness_score",
                    models.FloatField(
                        default=0.0, help_text="Readiness score (0-100%)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("NEEDS_DOCUMENTS", "Needs Documents"),
                            ("NEEDS_REVIEW", "Needs Officer Review"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customs_compliance_checks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment_id", "status"],
                        name="customs_com_shipmen_dd9233_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomsChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requirement_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("mandatory", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UPLOADED", "Uploaded"),
                            ("VERIFIED", "Verified"),
                            ("WAIVED", "Waived"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("document_required", models.BooleanField(default=False)),
                ("document_uploaded", models.BooleanField(default=False)),
                (
                    "evidence",
                    models.TextField(
                        blank=True, help_text="Regulatory proof/evidence statement"
                    ),
                ),
                (
                    "citation",
                    models.TextField(
                        blank=True,
                        help_text="Legal clause or regulation citation reference",
                    ),
                ),
                ("reviewer_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="customs.customscompliancecheck",
                    ),
                ),
            ],
            options={
                "db_table": "customs_checklist_items",
                "ordering": ["-mandatory", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomsDocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="e.g. COO, COMMERCIAL_INVOICE, MSDS, PHYTOSANITARY",
                        max_length=64,
                    ),
                ),
                ("document_name", models.CharField(max_length=128)),
                ("mandatory", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "accepted_formats",
                    models.CharField(default="PDF,PNG,JPG,DOCX", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customs_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="customs.customsrequirement",
                    ),
                ),
            ],
            options={
                "db_table": "customs_document_requirements",
            },
        ),
        migrations.CreateModel(
            name="HSCodeReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hs_code",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("description", models.TextField()),
                ("chapter", models.CharField(blank=True, max_length=8)),
                ("heading", models.CharField(blank=True, max_length=8)),
                ("subheading", models.CharField(blank=True, max_length=8)),
                (
                    "commodity_type",
                    models.CharField(default="General Cargo", max_length=64),
                ),
                ("restricted", models.BooleanField(default=False)),
                ("prohibited", models.BooleanField(default=False)),
                ("country", models.CharField(default="GLOBAL", max_length=64)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("source", models.CharField(default="WCO", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hs_code_references",
                "ordering": ["hs_code"],
                "indexes": [
                    models.Index(
                        fields=["commodity_type"], name="hs_code_ref_commodi_a2c6b4_idx"
                    ),
                    models.Index(
                        fields=["restricted", "prohibited"],
                        name="hs_code_ref_restric_a9cda8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegulationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=64)),
                (
                    "authority",
                    models.CharField(
                        help_text="e.g. US_CBP, EU_TAXUD, CBIC_INDIA", max_length=128
                    ),
                ),
                (
                    "document_type",
                    models.CharField(default="TARIFF_SCHEDULE", max_length=64),
                ),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "source_name",
                    models.CharField(
                        default="Official Customs Authority", max_length=128
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=32)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Full text of regulatory document or chapter"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DRAFT", "Draft"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "regulation_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["country", "authority"],
                        name="regulation__country_7a9df0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="regulation__status_32f3bf_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="customsrequirement",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customs.regulationdocument",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.CharField(db_index=True, max_length=128)),
                ("document_type", models.CharField(max_length=64)),
                ("file_name", models.CharField(max_length=255)),
                ("file_url", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                ("uploaded_by", models.CharField(blank=True, max_length=128)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified & Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="customs.customschecklistitem",
                    ),
                ),
                (
                    "customs_check",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="customs.customscompliancecheck",
                    ),
                ),
            ],
            options={
                "db_table": "shipment_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RegulationChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField(default=0)),
                ("content", models.TextField()),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Dense vector representation (float array)",
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "regulation_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="customs.regulationdocument",
                    ),
                ),
            ],
            options={
                "db_table": "regulation_chunks",
                "ordering": ["regulation_document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["regulation_document", "chunk_index"],
                        name="regulation__regulat_e8d6b2_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customsrequirement",
            index=models.Index(
                fields=["origin_country", "destination_country"],
                name="customs_req_origin__391a40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customsrequirement",
            index=models.Index(
                fields=["hs_code", "active"], name="customs_req_hs_code_9fad16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentdocument",
            index=models.Index(
                fields=["shipment_id", "document_type"],
                name="shipment_do_shipmen_a7454c_idx",
            ),
        ),
    ]
