# Generated by Django 6.0.7 on 2026-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentdocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="shipment_documents/%Y/%m/"
            ),
        ),
    ]
