# Generated by Django 6.0.7 on 2026-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customs", "0002_shipmentdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentdocument",
            name="agent_company",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="agent_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="agent_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="agent_reviewed_by",
            field=models.CharField(blank=True, default="", max_length=190),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="agent_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("VERIFIED", "Verified & Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="viewed_by",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
