# Generated by Django 6.0.7 on 2026-09-08 17:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreightCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=190)),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "modes",
                    models.JSONField(
                        default=list,
                        help_text='Transport modes served, e.g. ["ocean", "air"].',
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Headline service, e.g. 'MECL Service - weekly sailing'.",
                        max_length=190,
                    ),
                ),
                (
                    "headquarters",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                (
                    "on_time_performance",
                    models.FloatField(
                        blank=True, help_text="Schedule reliability, 0-100.", null=True
                    ),
                ),
                (
                    "average_response_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Typical agent verification turnaround.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "freight_companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AGENT", "Company Agent"),
                            ("MANAGER", "Company Manager"),
                        ],
                        default="AGENT",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="companies.freightcompany",
                    ),
                ),
            ],
            options={
                "db_table": "company_agents",
                "ordering": ["company__name", "user_email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "user_email"),
                        name="unique_agent_per_company",
                    )
                ],
            },
        ),
    ]
