# Generated by Django 6.0.7 on 2026-09-08 17:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyRateCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        default="ocean",
                        help_text="Transport mode these terms apply to.",
                        max_length=24,
                    ),
                ),
                (
                    "base_booking_fee",
                    models.FloatField(
                        default=0.0,
                        help_text="Flat charge per booking, before any variable cost.",
                    ),
                ),
                (
                    "rate_per_km",
                    models.FloatField(
                        default=0.0,
                        help_text="Line-haul rate applied to the routed distance.",
                    ),
                ),
                (
                    "rate_per_kg",
                    models.FloatField(
                        default=0.0, help_text="Rate applied to chargeable weight."
                    ),
                ),
                (
                    "fuel_surcharge_pct",
                    models.FloatField(
                        default=10.0,
                        help_text="Bunker adjustment, percent of line haul.",
                    ),
                ),
                (
                    "handling_fee",
                    models.FloatField(
                        default=0.0, help_text="Terminal handling and stevedoring."
                    ),
                ),
                (
                    "documentation_fee",
                    models.FloatField(
                        default=0.0, help_text="Bill of lading and manifest issuance."
                    ),
                ),
                (
                    "minimum_charge",
                    models.FloatField(
                        default=0.0,
                        help_text="Floor price; the offer never falls below this.",
                    ),
                ),
                (
                    "transit_days_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Days added to or removed from the routed transit estimate.",
                    ),
                ),
                (
                    "validity_days",
                    models.IntegerField(
                        default=14,
                        help_text="How long this company's offer stays valid.",
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_cards",
                        to="companies.freightcompany",
                    ),
                ),
            ],
            options={
                "db_table": "company_rate_cards",
                "ordering": ["company__name", "mode"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "mode"),
                        name="unique_rate_card_per_company_mode",
                    )
                ],
            },
        ),
    ]
