# Generated by Django 6.0.7 on 2026-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_companyratecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="freightcompany",
            name="manager_approval_high_risk",
            field=models.BooleanField(
                default=False,
                help_text="HIGH and CRITICAL risk shipments need a manager.",
            ),
        ),
        migrations.AddField(
            model_name="freightcompany",
            name="manager_approval_threshold",
            field=models.FloatField(
                blank=True,
                help_text="Offers above this total (INR) need a manager.",
                null=True,
            ),
        ),
    ]
