# Generated by Django 5.0.6 on 2026-08-26 05:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=128)),
                ("alert_type", models.CharField(default="ALL", max_length=64)),
                ("min_severity", models.CharField(default="MEDIUM", max_length=20)),
                ("email_enabled", models.BooleanField(default=True)),
                ("teams_enabled", models.BooleanField(default=False)),
                ("slack_enabled", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alert_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="IntegrationSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=64)),
                ("integration_type", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("records_processed", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "integration_sync_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataFreshness",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=64)),
                (
                    "data_type",
                    models.CharField(
                        help_text="e.g. WEATHER_FORECAST, TARIFF_SCHEDULE, PORT_CONGESTION",
                        max_length=64,
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("record_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy & Fresh"),
                            ("DEGRADED", "Degraded / Stale"),
                            ("OUTAGE", "Outage / Sync Failure"),
                        ],
                        default="HEALTHY",
                        max_length=20,
                    ),
                ),
                (
                    "freshness_seconds",
                    models.IntegerField(default=0, help_text="Data age lag in seconds"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_freshness_logs",
                "ordering": ["provider", "data_type"],
                "unique_together": {("provider", "data_type")},
            },
        ),
    ]
