# Generated by Django 5.0.6 on 2026-08-26 05:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShipmentRiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.CharField(db_index=True, max_length=128)),
                (
                    "quote_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "weather_score",
                    models.FloatField(
                        default=0.0, help_text="Weather risk score (0-100)"
                    ),
                ),
                (
                    "customs_score",
                    models.FloatField(
                        default=0.0, help_text="Customs risk score (0-100)"
                    ),
                ),
                (
                    "route_score",
                    models.FloatField(
                        default=0.0, help_text="Route risk score (0-100)"
                    ),
                ),
                (
                    "port_score",
                    models.FloatField(
                        default=0.0, help_text="Port congestion risk score (0-100)"
                    ),
                ),
                (
                    "cargo_score",
                    models.FloatField(
                        default=0.0, help_text="Cargo sensitivity risk score (0-100)"
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        default=0.0, help_text="Weighted composite risk score (0-100)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk (0-30)"),
                            ("MEDIUM", "Medium Risk (31-60)"),
                            ("HIGH", "High Risk (61-80)"),
                            ("CRITICAL", "Critical Risk (81-100)"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.95, help_text="Confidence metric (0.0 to 1.0)"
                    ),
                ),
                (
                    "explanation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured explainability breakdown and narrative",
                    ),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "model_version",
                    models.CharField(default="v1.0-composite", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "shipment_risk_assessments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment_id", "created_at"],
                        name="shipment_ri_shipmen_d009bc_idx",
                    ),
                    models.Index(
                        fields=["overall_score"], name="shipment_ri_overall_9b5a25_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "factor_type",
                    models.CharField(
                        choices=[
                            ("WEATHER", "Weather & Ocean"),
                            ("CUSTOMS", "Customs & Regulatory"),
                            ("ROUTE", "Transit & Chokepoint"),
                            ("PORT", "Port Congestion & Dwell"),
                            ("CARGO", "Cargo & Commodity Type"),
                        ],
                        max_length=32,
                    ),
                ),
                ("factor_name", models.CharField(max_length=128)),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="Normalized factor score (0-100)"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.2, help_text="Configured factor weight (0.0 - 1.0)"
                    ),
                ),
                (
                    "contribution",
                    models.FloatField(
                        default=0.0,
                        help_text="Absolute points contributed to overall score",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Plain-English explanation of why this factor received this score"
                    ),
                ),
                ("source", models.CharField(default="Risk Engine", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factors",
                        to="risk.shipmentriskassessment",
                    ),
                ),
            ],
            options={
                "db_table": "risk_factors",
                "ordering": ["-contribution"],
            },
        ),
        migrations.CreateModel(
            name="RiskAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shipment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "quote_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(default="RISK_THRESHOLD_BREACH", max_length=64),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("source", models.CharField(default="Risk Engine", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="risk.shipmentriskassessment",
                    ),
                ),
            ],
            options={
                "db_table": "risk_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"],
                        name="risk_alerts_status_6be3ca_idx",
                    )
                ],
            },
        ),
    ]
