# Generated by Django 6.0.7 on 2026-09-04 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "recipient_role",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SHIPMENT", "Shipment"),
                            ("QUOTE", "Quote"),
                            ("RISK", "Risk"),
                            ("CUSTOMS", "Customs"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=16,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("link", models.CharField(blank=True, default="", max_length=256)),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_id", "read"],
                        name="notificatio_recipie_6e3964_idx",
                    ),
                    models.Index(
                        fields=["recipient_role", "read"],
                        name="notificatio_recipie_6e6969_idx",
                    ),
                ],
            },
        ),
    ]
