"""The Quote Engine (PDF section 3, step 9).

"Combines shipment, route, prices and risk into a draft quote."

This is the join point for M1, M2 and M3. It drives the shipment through the
status flow the spec defines, runs the orchestrator, persists every AI output on
the Quote, applies the risk policy gate, and hands the result to the Freight
Agent for human review.
"""

import logging

from audit import service as audit_service
from notifications import service as notify
from orchestrator.service import AIOrchestrator

from . import lifecycle
from .models import Quote

logger = logging.getLogger(__name__)


class QuoteEngine:
    @classmethod
    def generate(cls, shipment, actor=None) -> Quote:
        """Run the pipeline and return a persisted, fully-populated Quote."""
        actor = actor or {"id": "system", "role": "system", "email": ""}

        # 1. Shipment enters analysis (PDF section 10 status flow).
        lifecycle.apply_shipment_status(
            shipment, lifecycle.SHIPMENT_STATUS_PROCESSING, actor=actor,
            reason="Quote requested; dispatched to AI orchestrator.",
        )

        # 2. Every agent runs here.
        analysis = AIOrchestrator.analyze(
            shipment,
            triggered_by=f"{actor.get('role', 'system')}:{actor.get('id', 'system')}",
        )

        lifecycle.apply_shipment_status(
            shipment, lifecycle.SHIPMENT_STATUS_ANALYZED, actor=actor,
            reason="AI analysis complete.",
        )

        route = analysis["route"]
        pricing = analysis["pricing"]
        weather = analysis["weather"]
        customs = analysis["customs"]
        risk = analysis["risk"]
        recommendation = analysis["recommendation"]
        breakdown = pricing.get("breakdown") or {}

        # 3. Build the quote. Created as GENERATED so the documented flow
        #    DRAFT -> GENERATED -> PENDING_REVIEW is genuinely traversed.
        quote = Quote.objects.create(
            shipment=shipment,
            customer_id=shipment.customer_id,
            distance=route["distance_km"],
            base_price=breakdown.get("base_price", 0.0),
            distance_charge=breakdown.get("distance_charge", 0.0),
            weight_charge=breakdown.get("weight_charge", 0.0),
            fuel_charge=breakdown.get("fuel_charge", 0.0),
            total_price=breakdown.get("total_price", 0.0),
            currency=pricing.get("currency", "USD"),
            status=lifecycle.QUOTE_STATUS_GENERATED,
            # M1 route intelligence
            estimated_transit_days=route["transit_days"],
            route_id=route.get("route_id", ""),
            route_path=route.get("path_display", ""),
            carrier=route.get("carrier", ""),
            # M2 pricing intelligence
            ai_predicted_price=pricing.get("ai_predicted_price"),
            recommended_price=recommendation["recommended_price"],
            pricing_strategy=recommendation.get("strategy", ""),
            ml_status=pricing.get("ml_status", "UNAVAILABLE"),
            # M3 risk intelligence
            weather_risk_score=weather.get("risk_score"),
            customs_risk_score=customs.get("risk_score"),
            route_risk_score=risk.get("route_score"),
            overall_risk_score=risk.get("overall_score"),
            overall_risk_level=risk.get("risk_level", ""),
            policy_action=risk.get("policy_action", ""),
            requires_human_review=not risk.get("can_issue_quote", False),
            analysis=analysis,
        )

        audit_service.record(
            actor_id=actor.get("id", "system"),
            actor_role=actor.get("role", "system"),
            actor_email=actor.get("email", ""),
            action=audit_service.QUOTE_GENERATED,
            entity_type="QUOTE",
            entity_id=quote.id,
            reason="Generated by the AI quote engine.",
            context={
                "shipment_id": shipment.id,
                "rule_price": pricing.get("rule_price"),
                "ai_predicted_price": pricing.get("ai_predicted_price"),
                "recommended_price": recommendation["recommended_price"],
                "ml_status": pricing.get("ml_status"),
                "overall_risk": risk.get("risk_level"),
                "policy_action": risk.get("policy_action"),
                "degraded_agents": analysis.get("degraded_agents", []),
                "orchestration_run_id": analysis.get("run_id"),
            },
        )

        # 4. Human review is mandatory in this workflow (PDF section 3, step 10),
        #    so every quote lands in the agent's queue.
        lifecycle.apply_quote_status(
            quote,
            lifecycle.QUOTE_STATUS_PENDING_REVIEW,
            actor=actor,
            reason=risk.get("policy_message", "Awaiting Freight Agent review."),
        )

        lifecycle.apply_shipment_status(
            shipment, lifecycle.SHIPMENT_STATUS_QUOTED, actor=actor,
            reason=f"Quote {quote.id} generated.",
        )

        cls._notify(shipment, quote, analysis)
        return quote

    # ------------------------------------------------------------------

    @classmethod
    def _notify(cls, shipment, quote, analysis):
        """Fan out the events this quote should raise across the portals."""
        risk = analysis["risk"]
        customs = analysis["customs"]
        weather = analysis["weather"]

        notify.notify_user(
            shipment.customer_id,
            "Quote generated and under review",
            f"Quote {quote.id} for {shipment.origin} to {shipment.destination} "
            f"is being reviewed by our freight team.",
            category="QUOTE",
            severity="INFO",
            entity_type="QUOTE",
            entity_id=quote.id,
            link="/dashboard/my-quotes",
        )

        notify.notify_role(
            "agent",
            f"New quote awaiting review: {quote.id}",
            f"{shipment.origin} to {shipment.destination} - "
            f"{risk.get('risk_level', 'UNKNOWN')} risk, "
            f"recommended {quote.currency} {quote.recommended_price:,.2f}.",
            category="QUOTE",
            severity="WARNING" if quote.requires_human_review else "INFO",
            entity_type="QUOTE",
            entity_id=quote.id,
            link="/dashboard/quote-review",
        )

        # Core scenario 6 -- a high weather risk raises an alert.
        if weather.get("risk_score", 0) >= 60:
            notify.notify_role(
                "agent",
                "High weather risk on quoted route",
                f"{weather.get('summary', '')} Route: {analysis['route'].get('path_display', '')}.",
                category="RISK",
                severity="WARNING",
                entity_type="QUOTE",
                entity_id=quote.id,
                link="/dashboard/risk-analysis",
            )

        # Core scenario 7 -- missing customs documents require officer action.
        missing = customs.get("missing_documents") or []
        if missing or customs.get("status") in ("NEEDS_DOCUMENTS", "REJECTED"):
            notify.notify_role(
                "customs",
                f"Customs action required: {shipment.id}",
                f"{len(missing)} mandatory document(s) outstanding: {', '.join(missing[:4]) or 'see checklist'}.",
                category="CUSTOMS",
                severity="WARNING",
                entity_type="SHIPMENT",
                entity_id=shipment.id,
                link="/dashboard/document-verification",
            )

        # Core scenario 8 -- high composite risk demands stronger review.
        if risk.get("risk_level") in ("HIGH", "CRITICAL"):
            notify.notify_role(
                "admin",
                f"{risk['risk_level']} composite risk on {shipment.id}",
                risk.get("policy_message", ""),
                category="RISK",
                severity="CRITICAL" if risk["risk_level"] == "CRITICAL" else "WARNING",
                entity_type="QUOTE",
                entity_id=quote.id,
                link="/dashboard/risk-intelligence",
            )
