# Generated by Django 5.0.6 on 2026-08-26 13:31

import django.db.models.deletion
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=quotes.models.generate_shipment_id,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=64)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("origin", models.CharField(max_length=128)),
                ("destination", models.CharField(max_length=128)),
                (
                    "cargo_type",
                    models.CharField(default="General Cargo", max_length=128),
                ),
                ("weight", models.FloatField(help_text="Weight in kilograms (kg)")),
                ("volume", models.FloatField(help_text="Volume in cubic meters (cbm)")),
                (
                    "transport_mode",
                    models.CharField(
                        default="ocean",
                        help_text="ocean, air, road, rail",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("QUOTED", "Quoted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="CREATED",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=quotes.models.generate_quote_id,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=64)),
                (
                    "distance",
                    models.FloatField(
                        help_text="Distance in kilometers (km) or nautical miles"
                    ),
                ),
                (
                    "base_price",
                    models.FloatField(
                        help_text="Fixed base booking/terminal charge ($)"
                    ),
                ),
                (
                    "distance_charge",
                    models.FloatField(
                        help_text="Distance charge based on rate per km ($)"
                    ),
                ),
                (
                    "weight_charge",
                    models.FloatField(help_text="Weight charge based on mass ($)"),
                ),
                (
                    "fuel_charge",
                    models.FloatField(help_text="Fuel bunker / surcharge ($)"),
                ),
                (
                    "total_price",
                    models.FloatField(help_text="Total calculated price ($)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="quotes.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
