# Generated by Django 6.0.7 on 2026-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="ai_predicted_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="carrier",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="quote",
            name="currency",
            field=models.CharField(default="USD", max_length=8),
        ),
        migrations.AddField(
            model_name="quote",
            name="customs_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="estimated_transit_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="ml_status",
            field=models.CharField(
                default="UNAVAILABLE",
                help_text="PREDICTED when the ML model answered, FALLBACK_RULE when it did not.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="original_total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="overall_risk_level",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="quote",
            name="overall_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="policy_action",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
        migrations.AddField(
            model_name="quote",
            name="pricing_strategy",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
        migrations.AddField(
            model_name="quote",
            name="recommended_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="requires_human_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="review_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quote",
            name="reviewed_by",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="quote",
            name="route_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="quote",
            name="route_path",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="quote",
            name="route_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="weather_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="container_type",
            field=models.CharField(blank=True, default="40FT", max_length=32),
        ),
        migrations.AddField(
            model_name="shipment",
            name="hs_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("GENERATED", "Generated"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent to Customer"),
                    ("ACCEPTED", "Accepted by Customer"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                    ("PENDING", "Pending (Legacy)"),
                ],
                default="PENDING_REVIEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("ANALYZED", "Analyzed"),
                    ("QUOTED", "Quoted"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                    ("CREATED", "Created (Legacy)"),
                    ("APPROVED", "Approved (Legacy)"),
                    ("REJECTED", "Rejected (Legacy)"),
                    ("IN_TRANSIT", "In Transit (Legacy)"),
                    ("DELIVERED", "Delivered (Legacy)"),
                ],
                default="SUBMITTED",
                max_length=32,
            ),
        ),
    ]
