# Generated by Django 6.0.7 on 2026-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_quote_ai_predicted_price_quote_analysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="assigned_agent_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="quote",
            name="assigned_agent_name",
            field=models.CharField(blank=True, default="", max_length=190),
        ),
        migrations.AddField(
            model_name="quote",
            name="carrier_selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="selected_carrier",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
