# Generated by Django 6.0.7 on 2026-09-08 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_companyratecard"),
        (
            "quotes",
            "0003_quote_assigned_agent_email_quote_assigned_agent_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("base_freight", models.FloatField(default=0.0)),
                ("fuel_surcharge", models.FloatField(default=0.0)),
                ("handling_fee", models.FloatField(default=0.0)),
                ("documentation_fee", models.FloatField(default=0.0)),
                ("total_price", models.FloatField(default=0.0)),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("transit_days", models.IntegerField(blank=True, null=True)),
                (
                    "service_name",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Platform's suggested option among the offers.",
                    ),
                ),
                ("risk_level", models.CharField(blank=True, default="", max_length=16)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("SELECTED", "Selected by customer"),
                            ("NOT_SELECTED", "Not selected"),
                            ("EXPIRED", "Expired"),
                            ("WITHDRAWN", "Withdrawn by company"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="companies.freightcompany",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_quotes",
                        to="quotes.quote",
                    ),
                ),
                (
                    "rate_card",
                    models.ForeignKey(
                        blank=True,
                        help_text="Terms this offer was priced from, kept for audit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="companies.companyratecard",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_quotes",
                        to="quotes.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "company_quotes",
                "ordering": ["total_price"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "status"],
                        name="company_quo_shipmen_29835b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quote", "company"),
                        name="unique_offer_per_company_per_quote",
                    )
                ],
            },
        ),
    ]
