# Generated by Django 6.0.7 on 2026-09-09 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("companies", "0002_companyratecard"),
        (
            "quotes",
            "0003_quote_assigned_agent_email_quote_assigned_agent_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=64)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("selected_total_price", models.FloatField()),
                ("selected_currency", models.CharField(default="INR", max_length=8)),
                ("selected_transit_days", models.IntegerField(blank=True, null=True)),
                ("selected_valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUOTE_OPTIONS_AVAILABLE", "Quote options available"),
                            ("QUOTE_SELECTED", "Quote selected by customer"),
                            (
                                "PENDING_COMPANY_VERIFICATION",
                                "Pending company verification",
                            ),
                            ("UNDER_VERIFICATION", "Under verification"),
                            ("AWAITING_CUSTOMER_INFO", "Awaiting customer information"),
                            ("REVISION_PENDING_CUSTOMER", "Revision pending customer"),
                            ("REVISION_ACCEPTED", "Revision accepted"),
                            ("APPROVED", "Approved by company"),
                            ("REJECTED", "Rejected by company"),
                            ("ESCALATED", "Escalated for manager approval"),
                            ("BOOKING_CONFIRMED", "Booking confirmed"),
                            ("BOOKING_CANCELLED", "Booking cancelled"),
                            ("RESELECT_QUOTE", "Customer may select another option"),
                        ],
                        default="QUOTE_SELECTED",
                        max_length=40,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False once superseded, so a shipment keeps one live selection.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="companies.freightcompany",
                    ),
                ),
                (
                    "company_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="booking.companyquote",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="quotes.quote",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="quotes.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "quote_selections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=40)),
                ("new_status", models.CharField(max_length=40)),
                (
                    "changed_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "changed_by_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("context", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="booking.quoteselection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "status history",
                "db_table": "selection_status_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "assigned_agent_email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "assigned_agent_name",
                    models.CharField(blank=True, default="", max_length=190),
                ),
                (
                    "decided_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("decision_reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUOTE_OPTIONS_AVAILABLE", "Quote options available"),
                            ("QUOTE_SELECTED", "Quote selected by customer"),
                            (
                                "PENDING_COMPANY_VERIFICATION",
                                "Pending company verification",
                            ),
                            ("UNDER_VERIFICATION", "Under verification"),
                            ("AWAITING_CUSTOMER_INFO", "Awaiting customer information"),
                            ("REVISION_PENDING_CUSTOMER", "Revision pending customer"),
                            ("REVISION_ACCEPTED", "Revision accepted"),
                            ("APPROVED", "Approved by company"),
                            ("REJECTED", "Rejected by company"),
                            ("ESCALATED", "Escalated for manager approval"),
                            ("BOOKING_CONFIRMED", "Booking confirmed"),
                            ("BOOKING_CANCELLED", "Booking cancelled"),
                            ("RESELECT_QUOTE", "Customer may select another option"),
                        ],
                        default="PENDING_COMPANY_VERIFICATION",
                        max_length=40,
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="companies.freightcompany",
                    ),
                ),
                (
                    "selection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="booking.quoteselection",
                    ),
                ),
            ],
            options={
                "db_table": "verification_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("SHIPMENT", "Shipment details"),
                            ("CARGO", "Cargo"),
                            ("CAPACITY", "Capacity"),
                            ("ROUTE", "Route"),
                            ("SCHEDULE", "Schedule"),
                            ("DOCUMENTS", "Documents"),
                            ("COMMERCIAL", "Commercial"),
                            ("RISK", "Risk context"),
                            ("VALIDITY", "Quote validity"),
                        ],
                        max_length=24,
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not yet checked"),
                            ("PASS", "Confirmed"),
                            ("ATTENTION", "Needs attention"),
                            ("FAIL", "Cannot be met"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "checked_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="booking.verificationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "verification_checks",
                "ordering": ["request", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="quoteselection",
            index=models.Index(
                fields=["shipment", "is_active"], name="quote_selec_shipmen_d014c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoteselection",
            index=models.Index(
                fields=["company", "status"], name="quote_selec_company_c30fab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                fields=["company", "status"], name="verificatio_company_39756a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationcheck",
            constraint=models.UniqueConstraint(
                fields=("request", "area"), name="unique_check_area_per_request"
            ),
        ),
    ]
