# Generated by Django 6.0.7 on 2026-09-09 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_quoteselection_statushistory_verificationrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="requested_information",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="QuoteRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("original_total_price", models.FloatField()),
                ("original_transit_days", models.IntegerField(blank=True, null=True)),
                ("revised_total_price", models.FloatField()),
                ("revised_transit_days", models.IntegerField(blank=True, null=True)),
                ("revised_base_freight", models.FloatField(blank=True, null=True)),
                ("revised_fuel_surcharge", models.FloatField(blank=True, null=True)),
                ("revised_handling_fee", models.FloatField(blank=True, null=True)),
                ("revised_documentation_fee", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(default="INR", max_length=8)),
                (
                    "reason",
                    models.TextField(help_text="Why the company changed the terms."),
                ),
                (
                    "created_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CUSTOMER", "Awaiting customer response"),
                            ("ACCEPTED", "Accepted by customer"),
                            ("DECLINED", "Declined by customer"),
                            ("SUPERSEDED", "Replaced by a later revision"),
                        ],
                        default="PENDING_CUSTOMER",
                        max_length=20,
                    ),
                ),
                ("customer_responded_at", models.DateTimeField(blank=True, null=True)),
                ("customer_response_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="booking.verificationrequest",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="booking.quoteselection",
                    ),
                ),
            ],
            options={
                "db_table": "quote_revisions",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("selection", "revision_number"),
                        name="unique_revision_number_per_selection",
                    )
                ],
            },
        ),
    ]
