# Generated by Django 6.0.7 on 2026-09-09 11:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_verificationrequest_requested_information_and_more"),
        ("companies", "0002_companyratecard"),
        (
            "quotes",
            "0003_quote_assigned_agent_email_quote_assigned_agent_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("customer_id", models.CharField(db_index=True, max_length=64)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("agreed_total_price", models.FloatField()),
                ("agreed_currency", models.CharField(default="INR", max_length=8)),
                ("agreed_transit_days", models.IntegerField(blank=True, null=True)),
                ("was_revised", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="CONFIRMED",
                        max_length=16,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="companies.freightcompany",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="quotes.quote",
                    ),
                ),
                (
                    "selection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking",
                        to="booking.quoteselection",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="quotes.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-confirmed_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"], name="bookings_company_9d1bb6_idx"
                    ),
                    models.Index(
                        fields=["customer_id", "status"],
                        name="bookings_custome_b789e2_idx",
                    ),
                ],
            },
        ),
    ]
