# Generated by Django 6.0.7 on 2026-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyquote",
            name="ai_market_factor",
            field=models.FloatField(
                blank=True,
                help_text="AI recommended price as a share of the rule price, applied to line haul.",
                null=True,
            ),
        ),
    ]
