# Generated by Django 6.0.7 on 2026-09-12 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_mirror_selection_status_onto_quotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteselection",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUOTE_OPTIONS_AVAILABLE", "Quote options available"),
                    ("QUOTE_SELECTED", "Quote selected by customer"),
                    ("PENDING_COMPANY_VERIFICATION", "Pending company verification"),
                    ("UNDER_VERIFICATION", "Under verification"),
                    ("AWAITING_CUSTOMER_INFO", "Awaiting customer information"),
                    ("REVISION_PENDING_CUSTOMER", "Revision pending customer"),
                    ("REVISION_ACCEPTED", "Revision accepted"),
                    ("APPROVED", "Approved by company"),
                    ("REJECTED", "Rejected by company"),
                    ("ESCALATED", "Escalated for manager approval"),
                    ("PENDING_CUSTOMS_REVIEW", "Pending customs clearance"),
                    ("CUSTOMS_CLEARED", "Cleared by customs, awaiting the customer"),
                    ("CUSTOMS_REJECTED", "Rejected by customs"),
                    ("BOOKING_CONFIRMED", "Booking confirmed"),
                    ("BOOKING_CANCELLED", "Booking cancelled"),
                    ("RESELECT_QUOTE", "Customer may select another option"),
                ],
                default="QUOTE_SELECTED",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUOTE_OPTIONS_AVAILABLE", "Quote options available"),
                    ("QUOTE_SELECTED", "Quote selected by customer"),
                    ("PENDING_COMPANY_VERIFICATION", "Pending company verification"),
                    ("UNDER_VERIFICATION", "Under verification"),
                    ("AWAITING_CUSTOMER_INFO", "Awaiting customer information"),
                    ("REVISION_PENDING_CUSTOMER", "Revision pending customer"),
                    ("REVISION_ACCEPTED", "Revision accepted"),
                    ("APPROVED", "Approved by company"),
                    ("REJECTED", "Rejected by company"),
                    ("ESCALATED", "Escalated for manager approval"),
                    ("PENDING_CUSTOMS_REVIEW", "Pending customs clearance"),
                    ("CUSTOMS_CLEARED", "Cleared by customs, awaiting the customer"),
                    ("CUSTOMS_REJECTED", "Rejected by customs"),
                    ("BOOKING_CONFIRMED", "Booking confirmed"),
                    ("BOOKING_CANCELLED", "Booking cancelled"),
                    ("RESELECT_QUOTE", "Customer may select another option"),
                ],
                default="PENDING_COMPANY_VERIFICATION",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="CustomsClearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for customs"),
                            ("CLEARED", "Cleared"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "officer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customs_clearance",
                        to="booking.quoteselection",
                    ),
                ),
            ],
            options={
                "db_table": "customs_clearances",
                "ordering": ["-created_at"],
            },
        ),
    ]
